# Generated by Django 3.2.15 on 2022-09-15 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_customer",
                to="vendor.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="society",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vendor_customer_society",
                to="vendor.society",
            ),
        ),
    ]
