# Generated by Django 3.2.15 on 2022-09-26 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0001_initial"),
        ("customer", "0002_auto_20220915_0600"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerOrder",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "id",
                    models.BigAutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("public_id", models.BigIntegerField(editable=False, unique=True)),
                ("shift", models.CharField(max_length=150)),
                ("milk_quantity", models.FloatField()),
                ("price", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[(1, "on_the_way"), (2, "delivered")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("order_date", models.DateField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cust_order",
                        to="customer.customer",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="vendor_delivery_partner_assign_order",
                        to="vendor.vendordeliverypartner",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_customer_order",
                        to="vendor.vendor",
                    ),
                ),
            ],
            options={
                "db_table": "customer_order",
            },
        ),
    ]
