# Generated by Django 3.2.15 on 2022-09-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('customer', '0003_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_customer_partner', to='vendor.vendordeliverypartner'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
