# Generated by Django 3.2.15 on 2022-09-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20220926_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
    ]
